# Generated by Django 2.0.5 on 2018-08-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0004_privatemessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='received_date',
        ),
    ]
