# Generated by Django 2.0.5 on 2018-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0010_auto_20180813_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='twitter_app/templates/twitter_app/avatars'),
        ),
    ]
