# Generated by Django 2.0.5 on 2018-08-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0014_auto_20180813_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='twitter_app/static/avatars'),
        ),
    ]
