# Generated by Django 2.0.5 on 2018-08-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0015_auto_20180813_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='twitter_app/static/avatars/no_avatar.jpg', upload_to='twitter_app/static/avatars'),
        ),
    ]
